In [1]:
# The Basic
import numpy as np

array = [[1,2,3],[4,5,6], [7,8,9]]
ndarray = np.array(array)


# The Basic
print(ndarray.ndim) 
print(ndarray.shape) 
print(ndarray.size)
print(ndarray.dtype) 
print(ndarray.itemsize) 
print(ndarray.data) 

2
(3, 3)
9
int64
8


In [2]:
# The Creation
from numpy import pi

c = np.array([[1, 2], [3, 4]], dtype=complex) #type specify

np.zeros((3,4))
np.ones((3,4))
np.empty((3,4), dtype="int16")

np.arange(10, 31, 5)
np.arange(0, 2.1, 0.3)  # it accepts float arguments


np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
x = np.linspace(0, 2 * pi, 100) 
# useful to evaluate function at lots of points
f = np.sin(x)


In [3]:
# Printing an array
# import sys

a = np.arange(6)                    # 1d array
print(a)
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)


# np.set_printoptions(threshold=sys.maxsize)  !!!!! prints full ndarray (sys module needed)
# print(np.arange(10000))
# print(np.arange(10000).reshape(100, 100))

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
# The Basic Operation

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)
c = a - b
print(c)
print(b**2)
print(10 * np.sin(a))
print(a < 35)



A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A * B)     # elementwise product
print(A @ B)     # matrix product
print(A.dot(B))  # another matrix product



[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [11]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
print(a)
b += a
print(b)
a += b  # b is not automatically converted to integer type

rg

Generator(PCG64) at 0x17CE72AD460

In [13]:
a = rg.random((2, 3))

print(a.sum())
print(a.min())
print(a.max())

3.1057109529998157
0.027559113243068367
0.8277025938204418


In [14]:
b = np.arange(12).reshape(3, 4)
b
b.sum(axis=0)     # sum of each column
b.min(axis=1)     # min of each row
b.cumsum(axis=1)  # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [15]:
B = np.arange(3)
B
np.exp(B)
np.sqrt(B)
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [16]:
a = np.arange(10)**3
a
a[2]
a[2:5]
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a
a[::-1]  # reversed a
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [21]:
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b
b[2, 3]
b[0:5, 1]  # each row in the second column of b
b[:, 1]    # equivalent to the previous example
b[1:3, :]  # each column in the second and third row of b

b[-1]   # the last row. Equivalent to b[-1, :]

for row in b:
    print(row)

for element in b.flat:
    print(element)    

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [19]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape
c[1, ...]  # same as c[1, :, :] or c[1]
c[..., 2]  # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])