In [16]:
import numpy as np
numpy_array = np.array([1,2,3])
arr4 = np.eye(6)
arr5 = np.arange(1,6,)
arr6 = np.linspace(1,4,4)
print(arr6)

[1. 2. 3. 4.]


In [28]:
#np array properties
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape, arr.dtype, arr.size, arr.ndim)
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(2, 3) int64 6 2
[[1. 2. 3.]
 [4. 5. 6.]] float64


In [37]:
# np operations 

#reshape
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
reshaped = arr.reshape(3,2)
print(reshaped)
flatten = arr.flatten()
print(flatten)


#Indexing
print(arr[1][1])
index = [2, 4]
print(flatten[index]) # fancy indexing 

print(arr[arr > 3]) # boolean indexing (condition based)




[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
5
[3 5]
[4 5 6]


[2, 3]

In [44]:
#Slicing 
arr = [1,2,3,4,5,6]
arr[1::2] #[start, end, step]

[2, 4, 6]

In [51]:
#Copy VS List
# arr = [1,2,3,4,5,6]
# sublist = arr[1:3]
# sublist[0] = 200
# print(sublist, arr)

np_arr = np.array([1,2,3,4,5])
sublist = np_arr[1:3]
sublist[0] = 200
print(sublist, np_arr)

[200   3] [  1 200   3   4   5]


In [53]:
#data types eg int64, float64,bool, complex64
np_arr1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(np_arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
#Multidimensional Array
arr2d = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(arr2d)
print(np.sum(arr2d, axis=0))
print(arr2d[0:2, 1:2])  #slicing perticular part in 2d Array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[[2]
 [5]]


In [65]:
arr3d = np.array([[[1,2,3], [4,5,6]],[[1,2,73], [40,5,6]], [[1,2,3], [4,5,6]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [40  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [69]:
print(arr3d[1,1,0])
print(arr3d[: ,0 , :])

40
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
# Vectorization & Broadcastiong

arr = np.array([1,2,3,4,5,6])
print(arr**2)
print(arr + 2)



[ 1  4  9 16 25 36]
[3 4 5 6 7 8]


In [74]:
arr = np.array([1,2,3])
arr2d = np.array([[1,2,3],[4,5,6]])

print(arr+arr2d)

[[2 4 6]
 [5 7 9]]


In [77]:
#Normalization 
arr2d = np.array([[1,2],[3,4]])
mean = np.mean(arr2d)
std_dev = np.std(arr2d)
normalized_arr = (arr2d - mean)/std_dev
print(normalized_arr)

[[-1.26491106 -0.63245553]
 [ 0.63245553  1.26491106]]
